version: '3'

services:

    api:
        build:
            context: ./api
            dockerfile: Dockerfile
        container_name: api
        image: uallasleles/flask
        restart: unless-stopped
        environment:
            - APP_ENV="prod"
            - APP_DEBUG="False"
            - APP_PORT=5000
            - MONGODB_DATABASE=${MONGODB_DATABASE}
            - MONGODB_USERNAME=${MONGODB_USERNAME}
            - MONGODB_PASSWORD=${MONGODB_PASSWORD}
            - MONGODB_HOSTNAME=${MONGODB_HOSTNAME}
        depends_on:
            - mongodb
        ports:
            - "5000:5000"
        networks:
            - frontend
            - backend

    mongodb:
        image: mongo
        container_name: mongodb
        restart: unless-stopped
        command: mongod --auth
        ports:
          - "27017:27017"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
            - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
            - MONGODB_DATA_DIR=${MONGODB_DATA_DIR}
            - MONDODB_LOG_DIR=${MONDODB_LOG_DIR}
        volumes:
            - mongodbdata:/data/db
        networks:
            - backend

    alpr:
        build:
            context: ./alpr
            args:
                - RTSP_SOURCE
            target: 'final-stage'
            dockerfile: Dockerfile
        image: uallasleles/alpr
        container_name: alpr
        environment:
            - RTSP_SOURCE=${RTSP_SOURCE}
        volumes:
            - .\data\alpr\:/var/lib/openalpr/
            - .\alpr\config\:/etc/openalpr/
            - .\alpr\config\stream.d\:/etc/openalpr/stream.d/
        ports:
            - "11300:11300"
            - "8355:8355"
            - "8554:8554"
        restart: unless-stopped
        depends_on:
            - mongodb
        networks:
          - backend
          - frontend
        cap_add:
            - SYS_NICE

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge

volumes:
    mongodbdata:
        driver: local