version: '3.9'

services:

  flask:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app
    image: flask
    restart: always
    environment:
      MONGODB_DATABASE: ${MONGODB_DATABASE}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_HOSTNAME: ${MONGODB_HOSTNAME}
      URL_ENDPOINT:     ${URL_ENDPOINT}
    volumes:
      - appdata:/var/www 
    depends_on:
      - mongodb
    ports:
      - "5000:5000"
    networks:
      - frontend
      - backend

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGODB_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    links:
      - mongodb
    networks:
      - backend

  mongodb:
    build:
      context: ./mongo
      dockerfile: Dockerfile
    image: mongo
    container_name: mongodb
    restart: always
    command: mongod --auth
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGODB_DATA: ${MONGODB_DATA}
      MONDODB_LOG: ${MONDODB_LOG}
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_PORT: ${APP_PORT}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_HOSTNAME: ${MONGODB_HOSTNAME}
    volumes:
      - ${HOSTDB_DATA}:${MONGODB_DATA} 
    networks:
      - backend

  webserver:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: webserver
    restart: always
    environment:
      APP_ENV: prod
      APP_NAME: webserver
      APP_DEBUG: "true"
      SERVICE_NAME: webserver
    ports:
      - "8080:80"
      - "6443:443"
    volumes:
      - nginxdata:/var/log/nginx
    depends_on:
      - flask
    networks:
      - frontend
      - backend

  openalpr:
    image: openalpr
    container_name: openalpr
    build:
      context: ./openalpr
      args:
        - RTSP_SOURCE
      target: 'final-stage'
      dockerfile: Dockerfile
    environment:
      CAM_NAME: ${CAM_NAME}
      RTSP_SOURCE: ${RTSP_SOURCE}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_HOSTNAME: ${MONGODB_HOSTNAME}
    volumes:
      - ${HOST_SOURCE_ALPR}:${ALPR_PATH_SOURCE} 
      - ${HOST_PATH_CONFIG}:${ALPR_PATH_CONFIG} 
      - ${HOST_PATH_DATA}:${ALPR_PATH_DATA} 
    ports:
      - "11300:11300"
      - "8355:8355"
      - "554:554"
    restart: always
    depends_on:
      - mongodb
    networks:
      - backend
      - frontend
    cap_add:
      - SYS_NICE

  task:
    build:
      context: ./task
      dockerfile: Dockerfile
    container_name: task
    image: task:1
    restart: always    
    environment:
      MONGODB_DATABASE: ${MONGODB_DATABASE}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_HOSTNAME: ${MONGODB_HOSTNAME}
      URL_ENDPOINT:     ${URL_ENDPOINT}
      ALPR_PATH_IMG:    ${ALPR_PATH_IMG}
    volumes:      
      - ${HOST_PATH_DATA}:${ALPR_PATH_DATA} 
    depends_on:
      - mongodb
    entrypoint: ["/wait-for-it.sh", "mongodb:27017"]
    networks: 
      - backend      

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:  
  mongodbdata:
    driver: local
  appdata:
    driver: local
  nginxdata:
    driver: local